-- V001__init.sql
-- Esquemas + tabla users (PostgreSQL) para configuración:
--   spring.flyway.default-schema: flyway
--   spring.flyway.schemas: bookme

-- 0) Asegurar esquemas
CREATE SCHEMA IF NOT EXISTS flyway;
CREATE SCHEMA IF NOT EXISTS bookme;

-- 1) Usar el esquema de negocio
SET search_path TO bookme;

-- 2) Tabla users (según UserEntity + AuditableEntity, role como String)
CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         VARCHAR(255)  NOT NULL UNIQUE,
  password      VARCHAR(255)  NOT NULL,
  firstname     VARCHAR(100)  NOT NULL,
  lastname      VARCHAR(100)  NOT NULL,
  phone_number  VARCHAR(30),
  is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
  role          VARCHAR(50)   NOT NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMP     NOT NULL DEFAULT NOW()
);

-- 3) Índices útiles
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users (created_at);

-- (Opcional) Evitar duplicados de email ignorando mayúsculas (si tu login es case-insensitive)
-- CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email_lower ON users (LOWER(email));
