-- V001__init.sql
-- Esquemas + tabla users (PostgreSQL) para configuración:
--   spring.flyway.default-schema: flyway
--   spring.flyway.schemas: bookme

-- 0) Asegurar esquemas
CREATE SCHEMA IF NOT EXISTS flyway;
CREATE SCHEMA IF NOT EXISTS bookme;

-- 1) Usar el esquema de negocio
SET search_path TO bookme;

-- 2) Tabla users (según UserEntity + AuditableEntity, role como String)
CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         VARCHAR(255)  NOT NULL UNIQUE,
  password      VARCHAR(255)  NOT NULL,
  firstname     VARCHAR(100)  NOT NULL,
  lastname      VARCHAR(100)  NOT NULL,
  phone_number  VARCHAR(30),
  is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
  role          VARCHAR(50)   NOT NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMP     NOT NULL DEFAULT NOW()
);

-- 3) Índices útiles
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users (created_at);

-- (Opcional) Evitar duplicados de email ignorando mayúsculas (si tu login es case-insensitive)
-- CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email_lower ON users (LOWER(email));


-- 4) Tabla customers (según CustomerEntity + AuditableEntity)
CREATE TABLE IF NOT EXISTS customers (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(100)  NOT NULL,
  last_name     VARCHAR(100)  NOT NULL,
  phone         VARCHAR(9)  NOT NULL,
  email         VARCHAR(100),
  created_at    TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMP     NOT NULL DEFAULT NOW()
);

-- 5) Tabla restaurants (según RestaurantEntity + AuditableEntity)
CREATE TABLE IF NOT EXISTS restaurants (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(150) NOT NULL,
  address     VARCHAR(255) NOT NULL,
  phone       VARCHAR(30)  NOT NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- Índices útiles
CREATE INDEX IF NOT EXISTS idx_restaurants_name ON restaurants (name);
CREATE INDEX IF NOT EXISTS idx_restaurants_created_at ON restaurants (created_at);

-- 6) Tabla intermedia para la relación N:M restaurant <-> user
CREATE TABLE IF NOT EXISTS restaurant_user (
  restaurant_id BIGINT NOT NULL,
  user_id       BIGINT NOT NULL,
  role          VARCHAR(50)   NOT NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
  -- Clave primaria compuesta evita duplicados (equivalente al unique(restaurant_id, user_id))
  PRIMARY KEY (restaurant_id, user_id),
  CONSTRAINT fk_ru_restaurant
    FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE,
  CONSTRAINT fk_ru_user
    FOREIGN KEY (user_id)       REFERENCES users (id)       ON DELETE CASCADE
);

-- Índice adicional para búsquedas por usuario -> restaurantes
CREATE INDEX IF NOT EXISTS idx_ru_user ON restaurant_user (user_id);

-- 7) opening_hours_default (simple y claro)
CREATE TABLE IF NOT EXISTS opening_hours_default (
  id             BIGSERIAL PRIMARY KEY,
  restaurant_id  BIGINT       NOT NULL REFERENCES restaurants (id) ON DELETE CASCADE,
  day_of_week    SMALLINT     NOT NULL CHECK (day_of_week BETWEEN 0 AND 6), -- 1=L ... 0=D
  opening_time   TIME,  -- solo hora
  closing_time   TIME,  -- solo hora
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ohd_restaurant_day
  ON opening_hours_default (restaurant_id, day_of_week);

-- (Opcional) evitar duplicados exactos del mismo tramo
-- CREATE UNIQUE INDEX IF NOT EXISTS ux_ohd_tramo
--   ON opening_hours_default (restaurant_id, day_of_week, opening_time, closing_time, close_next_day);
