-- V001__init.sql
-- Esquemas + tabla users (PostgreSQL) para configuración:
--   spring.flyway.default-schema: flyway
--   spring.flyway.schemas: bookme

-- 0) Asegurar esquemas
CREATE SCHEMA IF NOT EXISTS flyway;
CREATE SCHEMA IF NOT EXISTS bookme;

-- 1) Usar el esquema de negocio
SET search_path TO bookme;

-- 2) Tabla users (según UserEntity + AuditableEntity, role como String)
CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         VARCHAR(255)  NOT NULL UNIQUE,
  password      VARCHAR(255)  NOT NULL,
  firstname     VARCHAR(100)  NOT NULL,
  lastname      VARCHAR(100)  NOT NULL,
  phone_number  VARCHAR(30),
  is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
  role          VARCHAR(50)   NOT NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMP     NOT NULL DEFAULT NOW()
);

-- 3) Índices útiles
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users (created_at);

-- (Opcional) Evitar duplicados de email ignorando mayúsculas (si tu login es case-insensitive)
-- CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email_lower ON users (LOWER(email));


-- 4) Tabla customers (según CustomerEntity + AuditableEntity)
CREATE TABLE IF NOT EXISTS customers (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(100)  NOT NULL,
  last_name     VARCHAR(100)  NOT NULL,
  phone         VARCHAR(9)  NOT NULL,
  email         VARCHAR(100),
  created_at    TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMP     NOT NULL DEFAULT NOW()
);

-- 5) Tabla restaurants (según RestaurantEntity + AuditableEntity)
CREATE TABLE IF NOT EXISTS restaurants (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(150) NOT NULL,
  address     VARCHAR(255) NOT NULL,
  phone       VARCHAR(30)  NOT NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- Índices útiles
CREATE INDEX IF NOT EXISTS idx_restaurants_name ON restaurants (name);
CREATE INDEX IF NOT EXISTS idx_restaurants_created_at ON restaurants (created_at);

-- 6) Tabla intermedia para la relación N:M restaurant <-> user
CREATE TABLE IF NOT EXISTS restaurant_user (
  restaurant_id BIGINT NOT NULL,
  user_id       BIGINT NOT NULL,
  role          VARCHAR(50)   NOT NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
  -- Clave primaria compuesta evita duplicados (equivalente al unique(restaurant_id, user_id))
  PRIMARY KEY (restaurant_id, user_id),
  CONSTRAINT fk_ru_restaurant
    FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE,
  CONSTRAINT fk_ru_user
    FOREIGN KEY (user_id)       REFERENCES users (id)       ON DELETE CASCADE
);

-- Índice adicional para búsquedas por usuario -> restaurantes
CREATE INDEX IF NOT EXISTS idx_ru_user ON restaurant_user (user_id);

-- 7) opening_hours_default (simple y claro)
CREATE TABLE IF NOT EXISTS opening_hours_default (
  id             BIGSERIAL PRIMARY KEY,
  restaurant_id  BIGINT       NOT NULL REFERENCES restaurants (id) ON DELETE CASCADE,
  day_of_week    SMALLINT     NOT NULL CHECK (day_of_week BETWEEN 0 AND 6), -- 1=L ... 0=D
  opening_time   TIME,
  closing_time   TIME,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ohd_restaurant_day
  ON opening_hours_default (restaurant_id, day_of_week);

-- 8) Tabla tables (según TableEntity + AuditableEntity)
CREATE TABLE IF NOT EXISTS tables (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_number   INTEGER      NOT NULL,
  capacity       INTEGER      NOT NULL,
  restaurant_id  BIGINT       NOT NULL REFERENCES restaurants (id) ON DELETE CASCADE,
  observations   VARCHAR(500),               -- puede ser NULL
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Índices útiles
CREATE INDEX IF NOT EXISTS idx_tables_restaurant_id ON tables (restaurant_id);
CREATE INDEX IF NOT EXISTS idx_tables_number ON tables (table_number);
CREATE INDEX IF NOT EXISTS idx_tables_created_at ON tables (created_at);

-- (opcional) restricción única si no quieres duplicar mesas por restaurante
ALTER TABLE tables
  ADD CONSTRAINT ux_tables_restaurant_table_number
  UNIQUE (restaurant_id, table_number);

-- 9) Tabla reservations (según ReservationEntity + AuditableEntity)
CREATE TABLE IF NOT EXISTS reservations (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_time         TIMESTAMPTZ  NOT NULL,
  number_of_people  INTEGER      NOT NULL,
  status            VARCHAR(50)  NOT NULL,
  table_id          BIGINT       NOT NULL REFERENCES tables (id) ON DELETE CASCADE,
  customer_id       BIGINT       NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Índices útiles
CREATE INDEX IF NOT EXISTS idx_reservations_table_id ON reservations (table_id);
CREATE INDEX IF NOT EXISTS idx_reservations_customer_id ON reservations (customer_id);
CREATE INDEX IF NOT EXISTS idx_reservations_date_time ON reservations (date_time);
CREATE INDEX IF NOT EXISTS idx_reservations_created_at ON reservations (created_at);

