server:
  port: 8080

spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key}
      chat:
        client:
          connect-timeout: 1s
          read-timeout: 3s
          max-tokens: 80
        options:
          model: gpt-3.5-turbo # gpt-4o-mini, gpt-3.5-turbo, usar modelo local ligero tipo "qwen" o Distilbert?
          temperature: 0.7
  application:
    name: bookme-back
  datasource:
    url: jdbc:postgresql://localhost:5443/bookme
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: ${JWT_KEY:24Mn84.Mah3-45KamNDA2kLmaSDASJEND.34asfmn2358daskdJDSALKNe.12}
      expiration: 864000000

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

info:
  app:
    version: @project.version@

#Twilio
twilio:
  speech:
    confidence-threshold: 0.7

